export const ADD_LOCATION = 'ADD_LOCATION';
export const CHANGE_LAND_AVAILABILITY = 'CHANGE_LAND_AVAILABILITY';
export const SET_BUDGET = 'SET_BUDGET';
export const INC_PROGRESS_VALUE = 'INC_PROGRESS_VALUE';
export const DEC_PROGRESS_VALUE = 'DEC_PROGRESS_VALUE';
export const DEC_PROGRESS_VALUE_TO = 'DIC_PROGRESS_VALUE_TO';
export const SET_DISASTER_TYPE = 'SET_DISASTER_TYPE';