export const ADD_LOCATION = 'ADD_LOCATION';
export const CHANGE_LAND_AVAILABILITY = 'CHANGE_LAND_AVAILABILITY';
export const SET_BUDGET = 'SET_BUDGET';
export const SET_PROGRESS_VALUE = 'SET_PROGRESS_VALUE';

